default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: instagram_rails
  password: instagram_rails

development:
  <<: *default
  database: instagram_rails_development

test:
  <<: *default
  database: instagram_rails_test

production:
  <<: *default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DATABASE_NAME") { 'instagram_rails' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'instagram_rails' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'instagram_rails' } %>
